# Generated by Django 5.0.2 on 2024-04-09 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_heading_space_host_communicate_space_heading'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='space',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='space',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
